services:

  mysql:
    image: mysql:8.0
    container_name: java-spring-boot-vinavita-mysql
    restart: always
    environment:
      MYSQL_DATABASE: vinavita
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./var/logs/mysql:/var/log/mysql
    networks:
      - java-spring-boot-vinavita-network

  redis:
    image: redis:7.0.12-alpine
    container_name: java-spring-boot-vinavita-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass "secret"
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    networks:
      - java-spring-boot-vinavita-network

  redis-commander:
    image: rediscommander/redis-commander:redis-commander-210
    restart: always
    container_name: java-spring-boot-vinavita-redis-commander
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: default
      REDIS_PASSWORD: secret
      HTTP_USER: admin
      HTTP_PASSWORD: secret
    ports:
      - '6380:8081'
    networks:
      - java-spring-boot-vinavita-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: java-spring-boot-vinavita-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - '8080:80'
    networks:
      - java-spring-boot-vinavita-network

volumes:
  mysql-data:
  redis-data:

networks:
  java-spring-boot-vinavita-network:
    driver: bridge
